### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by kylewschulz** [YingyiYang/Stats506_public#1]
Completeness
- Has Group Member links
- Has week 1/week 4/5 activities 
- Good descriptions, may need to add desc. for week 4 at the moment 

Correctness
- All links work 
- Solutions are generally present, not 100% sure about week 1 part 2 

Style
- Style is pleasant, good use of bulleted lists 
- Week 1 scripts still have Prof. as author and week 4 scripts need author 
- Good comments, no run-on lines

**Comment by YingyiYang** [comment]
Author names changed.

**Comment by YingyiYang** [comment]
Author names changed.
